#search_module.py

popular_site = {
    "chennai": [
        "Fort St. George, Rajaji Road, Chennai – 600009",
        "Government Museum, Pantheon Road, Egmore, Chennai – 600008",
        "Vivekananda House, Kamarajar Salai, Triplicane, Chennai – 600005",
        "Kalakshetra Foundation, Kalakshetra Road, Thiruvanmiyur, Chennai – 600041",
        "Madras High Court, Parry's Corner, Chennai – 600104",
        "Kapaleeshwarar Temple, Mylapore, Chennai – 600004",
        "Parthasarathy Temple, Triplicane, Chennai – 600005",
        "Vadapalani Murugan Temple, Vadapalani, Chennai – 600026",
        "Santhome Basilica, Santhome High Road, Chennai – 600004",
        "St. Thomas Mount, St. Thomas Mount, Chennai – 600016",
        "Marina Beach, Kamarajar Salai, Chennai – 600005",
        "Elliot’s Beach, Besant Nagar, Chennai – 600090",
        "Thiruvanmiyur Beach, Thiruvanmiyur, Chennai – 600041",
        "Guindy National Park, Sardar Patel Road, Guindy, Chennai – 600025",
        "Theosophical Society, Adyar, Chennai – 600020",
        "Semmozhi Poonga, Cathedral Road, Teynampet, Chennai – 600086",
        "T. Nagar Shopping District, Thyagaraya Nagar, Chennai – 600017",
        "Express Avenue Mall, Whites Road, Royapettah, Chennai – 600014",
        "Phoenix Marketcity, Velachery Main Road, Velachery, Chennai – 600042",
        "DakshinaChitra, East Coast Road, Muttukadu, Chennai – 603112",
        "MGR Film City, Taramani, Chennai – 600113",
        "Arignar Anna Zoological Park (Vandalur Zoo), Grand Southern Trunk Road, Vandalur, Chennai – 600048",
        "Madras Crocodile Bank Trust, East Coast Road, Vadanemmeli, Chennai – 603104",
        "Thousand Lights Mosque, Peters Road, Royapettah, Chennai – 600014",
        "Valluvar Kottam, Kodambakkam High Road, Nungambakkam, Chennai – 600034",
        "Gandhi Mandapam, Sardar Patel Road, Adyar, Chennai – 600020",
        "Cholamandal Artists' Village, Injambakkam, Chennai – 600115",
        "Muttukadu Boat House, East Coast Road, Muttukadu, Chennai – 603112",
        "Covelong Beach, Kovalam, Chennai – 603112",
        "Ashtalakshmi Temple, Besant Nagar, Chennai – 600090",
        "Snow Kingdom, East Coast Road, Injambakkam, Chennai – 600115",
        "Breezy Beach, Valmiki Nagar, Chennai – 600041",
        "Kasimedu Beach, Royapuram, Chennai – 600013",
        "Chennai Rail Museum, New Avadi Road, Villivakkam, Chennai – 600023",
        "Birla Planetarium, Gandhi Mandapam Road, Kotturpuram, Chennai – 600025",
        "VGP Universal Kingdom, East Coast Road, Injambakkam, Chennai – 600115",
        "MGM Dizzee World, East Coast Road, Muttukadu, Chennai – 603112",
        "Mayajaal Multiplex, East Coast Road, Kanathur, Chennai – 603112",
        "Prarthana Drive-in Theatre, East Coast Road, Injambakkam, Chennai – 600115",
        "Anna Centenary Library, Kotturpuram, Chennai – 600085",
        "Tholkappia Poonga (Adyar Eco Park), Greenways Road, Adyar, Chennai – 600028",
        "Chennai Lighthouse, Marina Beach Road, Chennai – 600005",
        "St. Mary's Church, Fort St. George, Chennai – 600009",
        "Armenian Church, Armenian Street, George Town, Chennai – 600001",
        "St. Andrew's Church (The Kirk), Egmore, Chennai – 600008",
        "Sri Ramakrishna Math, Mylapore, Chennai – 600004",
        "National Art Gallery, Pantheon Road, Egmore, Chennai – 600008",
        "Birla Planetarium, Gandhi Mandapam Road, Kotturpuram, Chennai – 600025",
        "Anna Nagar Tower Park, Anna Nagar, Chennai – 600040",
        "Guindy Snake Park, Sardar Patel Road, Guindy, Chennai – 600022",
        "Chennai Marina Lighthouse, Marina Beach Road, Chennai – 600005"
    ],
     "ariyalur": [
        "Gangaikonda Cholapuram, Jayankondam, Ariyalur – 621802",
        "Karaivetti Bird Sanctuary, Karaivetti, Ariyalur – 621851",
        "Thirumazhapadi Vaidyanathaswami Temple, Thirumazhapadi, Ariyalur – 621851",
        "Kaliyuga Varadaraja Perumal Temple, Kallankurichi, Ariyalur – 621705",
        "Meenatchi Sundareswarar Temple, Melapaluvur, Ariyalur – 621707",
        "Siva Temple, Sendurai, Ariyalur – 621714",
        "Siva Temple, Sennivanam, Ariyalur – 621718",
        "Siva Temple, Sripurandan, Ariyalur – 621719",
        "Govindaputtur Temple, Govindaputtur, Ariyalur – 621701",
        "Elakurichi Adaikala Madha Shrine, Elakurichi, Ariyalur – 621715"
    ],
     "chengalpattu": [
        "Vedanthangal Bird Sanctuary, Vedanthangal, Chengalpattu – 603314",
        "Arignar Anna Zoological Park, Vandalur, Chennai – 600048",
        "Kandhaswamy Temple, Thiruporur, Chengalpattu – 603110",
        "Vedagiriswarar Temple, Thirukalukundram, Chengalpattu – 603109",
        "Nityakalyana Perumal Temple, Thiruvidanthai, Chengalpattu – 603112",
        "Srinivasa Perumal Temple, Semmanjeri, Chengalpattu – 603103",
        "Nandeesvarar Temple, Nandivaram-Guduvancheri, Chengalpattu – 603202",
        "Kolavai Lake, Near Chengalpattu Railway Station, Chengalpattu – 603001",
        "Nanmangalam Reserve Forest, Medavakkam, Chennai – 600100",
        "Pancha Rathas, Mahabalipuram, Chengalpattu – 603104",
        "Shore Temple, Mahabalipuram, Chengalpattu – 603104",
        "India Seashell Museum, Mahabalipuram, Chengalpattu – 603104",
        "DakshinaChitra Heritage Museum, Muttukadu, Chengalpattu – 603112",
        "Muttukadu Boat House, East Coast Road, Muttukadu, Chengalpattu – 603112",
        "Madurantakam Lake, Madurantakam, Chengalpattu – 603306",
        "Sri Maha Bhairavar Rudhra Alayam, Chengalpattu – 603001",
        "Vallam Hill Cave Temple, Vallam, Chengalpattu – 603002",
        "Gnanapureeswarar Temple, Thirumukkoodal, Chengalpattu – 603405",
        "Chathurbhuja Ramar Temple, Madurantakam, Chengalpattu – 603306",
        "Laurel Shopping Mall, Chengalpattu – 603001"
    ],
     "coimbatore": [
        "Adiyogi Shiva Statue, Isha Yoga Center, Velliangiri Foothills, Coimbatore – 641114",
        "Dhyanalinga Temple, Isha Yoga Center, Velliangiri Foothills, Coimbatore – 641114",
        "Marudhamalai Murugan Temple, Marudhamalai, Coimbatore – 641046",
        "Perur Pateeswarar Temple, Perur, Coimbatore – 641010",
        "Eachanari Vinayagar Temple, Eachanari, Coimbatore – 641021",
        "Koniamman Temple, Big Bazaar Street, Town Hall, Coimbatore – 641001",
        "Velliangiri Andavar Temple, Poondi, Coimbatore – 641114",
        "Anuvavi Subramaniar Temple, Kanuvai, Coimbatore – 641108",
        "Karamadai Ranganathar Temple, Karamadai, Coimbatore – 641104",
        "Arulmigu Patteeswarar Swamy Temple, Perur, Coimbatore – 641010",
        "Gass Forest Museum, Cowley Brown Road, RS Puram, Coimbatore – 641002",
        "G.D. Naidu Museum, Avinashi Road, Coimbatore – 641018",
        "Regional Science Centre, Codissia Road, Peelamedu, Coimbatore – 641014",
        "Kasthuri Sreenivasan Art Gallery & Textile Museum, Avinashi Road, Coimbatore – 641014",
        "VOC Park and Zoo, Jail Road, Gopalapuram, Coimbatore – 641018",
        "Black Thunder Water Theme Park, Mettupalayam, Coimbatore – 641305",
        "Kovai Kondattam Amusement Park, Siruvani Main Road, Kalampalayam, Coimbatore – 641010",
        "Maharaja Theme Park, Neelambur, Avinashi Road, Coimbatore – 641062",
        "Brookefields Mall, Dr. Krishnasamy Mudaliyar Road, Coimbatore – 641001",
        "Prozone Mall, Sathy Road, Saravanampatti, Coimbatore – 641035",
        "Fun Republic Mall, Avinashi Road, Peelamedu, Coimbatore – 641004",
        "Siruvani Waterfalls and Dam, Siruvani Hills, Coimbatore – 641114",
        "Vaideki Falls, Narasipuram, Coimbatore – 641109",
        "Sengupathi Falls, Perur, Coimbatore – 641010",
        "Aliyar Dam, Near Pollachi, Coimbatore – 642101",
        "Monkey Falls, Near Aliyar, Coimbatore – 642101",
        "Valparai Hill Station, Valparai, Coimbatore – 642127",
        "Anamalai Tiger Reserve, Pollachi, Coimbatore – 642101",
        "Parambikulam Wildlife Sanctuary, Anamalai Hills, Coimbatore – 642126",
        "Silent Valley National Park, Mannarkkad, Palakkad District, Kerala – 678582",
        "Kari Motor Speedway, Chettipalayam, Coimbatore – 641201",
        "Coimbatore Golf Club, Chettipalayam, Coimbatore – 641201",
        "Nehru Stadium, VOC Park, Coimbatore – 641018",
        "Valankulam Lake, Sungam Bypass Road, Coimbatore – 641001",
        "Singanallur Lake, Singanallur, Coimbatore – 641005",
        "Periyakulam Lake, Ukkadam, Coimbatore – 641001",
        "Botanical Garden, Tamil Nadu Agricultural University, Marudhamalai Road, Coimbatore – 641003",
        "Gandhi Park, Oppanakara Street, Coimbatore – 641001",
        "Thirumoorthy Hills, Udumalpet, Coimbatore – 642112",
        "Masani Amman Temple, Anaimalai, Pollachi, Coimbatore – 642104"
    ],
     "cuddalore": [
        "Pichavaram Mangrove Forest, Pichavaram, near Chidambaram, Cuddalore – 608102",
        "Silver Beach, Devanampattinam, Cuddalore – 607001",
        "Fort St. David, Devanampattinam, Cuddalore – 607001",
        "Padaleeswarar Temple, Thirupathiripuliyur, Cuddalore – 607002",
        "Devanathaswamy Temple, Thiruvanthipuram, Cuddalore – 607401",
        "Veeratteswarar Temple, Thiruvathigai, near Panruti, Cuddalore – 607106",
        "Bhu Varaha Swamy Temple, Srimushnam, Cuddalore – 608703",
        "Thillai Nataraja Temple, Chidambaram, Cuddalore – 608001",
        "Thillai Kali Temple, Chidambaram, Cuddalore – 608001",
        "Satyagnana Sabha (Vallalar Temple), Vadalur, Cuddalore – 607303",
        "Vamaneeswarar Temple, Thirumanikuzhi, Cuddalore – 607102",
        "Narthana Vallabeswarar Temple, Thirukoodalaiyathoor, Cuddalore – 606108",
        "Singirikudi Sri Lakshmi Narasimha Swami Temple, Singirikudi, Cuddalore – 607402",
        "Veeranam Lake, near Kattumannarkoil, Cuddalore – 608301",
        "Garden House (Clive House), Cuddalore – 607001"
    ],
      "dharmapuri": [
        "Hogenakkal Falls, Hogenakkal, Dharmapuri – 636810",
        "Theerthagirishwarar Temple, Theerthamalai, Harur Taluk, Dharmapuri – 636906",
        "Kottai Kovil (Mallikarjunar Temple), Fort Area, Dharmapuri – 636701",
        "Adiyamankottai Fort, Adiyamankottai, Dharmapuri – 636701",
        "Chenraya Perumal Temple, Adiyamankottai, Dharmapuri – 636701",
        "Hanuman Theertham, Near Theerthamalai, Harur Taluk, Dharmapuri – 636906",
        "Mount Carmel Church, Dharmapuri – 636701",
        "Sacred Heart Cathedral, Dharmapuri – 636701",
        "C.S.I Zion Church, Dharmapuri – 636701",
        "Karimangalam, Dharmapuri – 635111",
        "Mookanur Adi Srinivasa Perumal Temple, Mookanur, Dharmapuri – 636906",
        "Thenkaraikottai Fort (Tangrakottai), Near Pappireddipatti, Dharmapuri – 636905",
        "Kalyana Ramaswamy Temple, Thenkaraikottai, Dharmapuri – 636905",
        "Subramanya Siva Memorial, Papparapatti, Dharmapuri – 635302",
        "Kaveri River Viewpoint, Hogenakkal, Dharmapuri – 636810",
        "Crocodile Rehabilitation Centre, Hogenakkal, Dharmapuri – 636810",
        "Medicinal Garden, Hogenakkal, Dharmapuri – 636810",
        "Children’s Park, Hogenakkal, Dharmapuri – 636810",
        "Vatra Kulam (Everlasting Pond), Mookanur, Dharmapuri – 636906"
    ],
       "dindigul": [
        "Dindigul Fort, Fort Road, Dindigul – 624001",
        "Arulmigu Dhandayuthapani Swamy Temple, Palani Hills, Palani – 624601",
        "Soundararaja Perumal Temple, Thadikombu, Dindigul – 624005",
        "Abirami Amman Temple, Rock Fort, Dindigul – 624001",
        "Sirumalai Hills, Sirumalai, Dindigul – 624003",
        "Kodaikanal Lake, Kodaikanal, Dindigul – 624101",
        "Berijam Lake, Kodaikanal, Dindigul – 624101",
        "Thalaiyar Falls (Rat Tail Falls), Near Kodaikanal, Dindigul – 624101",
        "Silver Cascade Falls, Kodaikanal, Dindigul – 624101",
        "Pine Forest, Kodaikanal, Dindigul – 624101",
        "Guna Caves, Pillar Rocks Road, Kodaikanal – 624101",
        "Pillar Rocks, Kodaikanal, Dindigul – 624101",
        "Coaker's Walk, Kodaikanal, Dindigul – 624101",
        "Bryant Park, Lower Shola Road, Kodaikanal – 624101",
        "Kamarajar Sagar Dam, Athoor, Dindigul – 624701",
        "Begambur Big Mosque, Begambur, Dindigul – 624001",
        "St. Joseph's Church, St. Joseph's Road, Dindigul – 624001",
        "Sri Kottai Mariamman Kovil, Fort Area, Dindigul – 624001",
        "Anjaneyar Temple, Dindigul – 624001",
        "Chinnalapatti Handloom Weaving Village, Chinnalapatti, Dindigul – 624301",
        "Athoor Village, Athoor, Dindigul – 624701",
        "Vellimalai Murugan Temple, Sirumalai Hills, Dindigul – 624003",
        "Annai Velankanni Church, Sirumalai, Dindigul – 624003",
        "Observation Tower, Sirumalai Hills, Dindigul – 624003",
        "Sanjeevani Hills, Sirumalai, Dindigul – 624003",
        "Saathiyar Basin, Sirumalai, Dindigul – 624003"
    ],
       "erode": [
        "Thindal Murugan Temple, Thindal, Erode – 638012",
        "Sangameswarar Temple, Bhavani, Erode – 638301",
        "Chennimalai Murugan Temple, Chennimalai, Erode – 638051",
        "Bannari Amman Temple, Bannari, Sathyamangalam, Erode – 638401",
        "Magudeswarar Temple, Kodumudi, Erode – 638151",
        "Pariyur Kondathu Kaliamman Temple, Pariyur, Gobichettipalayam, Erode – 638476",
        "Pachaimalai Subramanya Swamy Temple, Gobichettipalayam, Erode – 638452",
        "Vellode Birds Sanctuary, Vellode, Erode – 638112",
        "Kodiveri Dam, Kodiveri, Gobichettipalayam, Erode – 638503",
        "Bhavanisagar Dam, Bhavanisagar, Sathyamangalam, Erode – 638451",
        "Varattupallam Dam, Varattupallam, Anthiyur, Erode – 638501",
        "Government Museum, VOC Park, Erode – 638003",
        "Karungalpalayam Ferry Station, Karungalpalayam, Erode – 638003",
        "Mahakavi Bharathi Memorial Library, Karungalpalayam, Erode – 638003",
        "Periya Mariamman Temple, Karungalpalayam, Erode – 638003",
        "Chinna Mariamman Temple, Karungalpalayam, Erode – 638003",
        "Subramaniasamy Temple, Karungalpalayam, Erode – 638003",
        "Kunderipallam Dam, Kunderipallam, Gobichettipalayam, Erode – 638476",
        "Bhavani Kuduthurai (Triveni Sangam), Bhavani, Erode – 638301"
    ],
         "kallakurichi": [
        "Kalvarayan Hills, Kalvarayan Hills Taluk, Kallakurichi – 606213",
        "Periyar Falls, Kalvarayan Hills, Kallakurichi – 606213",
        "Megham Falls, Kalvarayan Hills, Kallakurichi – 606213",
        "Sirukalur Falls, Kalvarayan Hills, Kallakurichi – 606213",
        "Gomukhi Dam, Gomukhi River, Kallakurichi – 606202",
        "Sri Veeratteswarar Temple, Thirukkoilur, Kallakurichi – 605757",
        "Ulagalantha Perumal Temple, Thirukkoilur, Kallakurichi – 605757",
        "Jambunatheshwarar Temple, Jambai Village, Tirukkoyilur Taluk, Kallakurichi – 605757",
        "Jambaimalai Jain Caves, Jambai Village, Tirukkoyilur Taluk, Kallakurichi – 605757",
        "Cholapandiyapuram Jain Caves, Cholapandiyapuram Village, Tirukkoyilur Taluk, Kallakurichi – 605757",
        "Melnaariyappanoor Church, Melnaariyappanoor, Kallakurichi – 606201",
        "Sivaganga Park, Kallakurichi Town, Kallakurichi – 606202",
        "Thirunarungondai Jain Caves, Thirunarungondai, Kallakurichi – 606206"
    ],
          "kancheepuram": [
        "Kailasanathar Temple, Pillaiyarpalayam, Kanchipuram – 631501",
        "Ekambareswarar Temple, Ekambaranathar Sannathi Street, Periya Kanchipuram, Kanchipuram – 631502",
        "Kamakshi Amman Temple, Kamakshi Amman Sannathi Street, Periya Kanchipuram, Kanchipuram – 631502",
        "Varadharaja Perumal Temple, Vishnu Kanchi, Kanchipuram – 631501",
        "Ulagalantha Perumal Temple, Big Kanchipuram, Kanchipuram – 631502",
        "Kanchi Kamakoti Peetham (Kanchi Mutt), Salai Street, Kanchipuram – 631502",
        "Kanchi Kudil (Heritage Museum), Sangeetha Mahal, Sangeetha Mahal Street, Kanchipuram – 631502",
        "Devarajaswami Temple, Vishnu Kanchi, Kanchipuram – 631501",
        "Vedanthangal Bird Sanctuary, Vedanthangal, Kanchipuram – 603314",
        "Vaikunta Perumal Temple, Big Kanchipuram, Kanchipuram – 631502",
        "Chitragupta Swamy Temple, Nellukara Street, Kanchipuram – 631502",
        "Thennangur Panduranga Temple, Thennangur, Vandavasi Taluk, Kanchipuram – 604408",
        "Kumarakottam Murugan Temple, Nellukara Street, Kanchipuram – 631502",
        "Sri Ashtabujakaram Temple, Big Kanchipuram, Kanchipuram – 631502",
        "Sri Deepa Prakasa Perumal Temple, Big Kanchipuram, Kanchipuram – 631502",
        "Sri Yathothkari Perumal Temple, Big Kanchipuram, Kanchipuram – 631502",
        "Sri Pandava Dhootha Perumal Temple, Big Kanchipuram, Kanchipuram – 631502",
        "Sri Vilakoli Perumal Temple, Big Kanchipuram, Kanchipuram – 631502",
        "Sri Pavala Vannar Temple, Big Kanchipuram, Kanchipuram – 631502",
        "Sri Vaikunta Perumal Temple, Big Kanchipuram, Kanchipuram – 631502"
    ],
           "kanniyakumari": [
        "Vivekananda Rock Memorial, Vavathurai, Kanyakumari – 629702",
        "Thiruvalluvar Statue, Vavathurai, Kanyakumari – 629702",
        "Bhagavathy Amman Temple, Beach Road, Kanyakumari – 629702",
        "Kanyakumari Beach, Beach Road, Kanyakumari – 629702",
        "Gandhi Memorial Mandapam, Beach Road, Kanyakumari – 629702",
        "Kamarajar Mani Mantapa Monument, Beach Road, Kanyakumari – 629702",
        "Tsunami Memorial Park, Beach Road, Kanyakumari – 629702",
        "Vattakottai Fort, Vattakottai, Kanyakumari – 629401",
        "Padmanabhapuram Palace, Padmanabhapuram, Thuckalay, Kanyakumari – 629175",
        "Udayagiri Fort, Puliyoorkurichi, Kanyakumari – 629403",
        "Mathur Hanging Trough (Aqueduct), Mathoor, Kanyakumari – 629164",
        "Thirparappu Waterfalls, Thirparappu, Kanyakumari – 629161",
        "Chitharal Jain Rock Cut Temple, Chitharal, Kanyakumari – 629151",
        "Sanguthurai Beach, Sanguthurai, Kanyakumari – 629501",
        "Olakaruvi Falls (Ullakaarvi), Olakaruvi, Kanyakumari – 629401",
        "Periyanayaki Shrine (Mary Matha Church), Thiruvithancode, Kanyakumari – 629174",
        "Thirunanthikarai Cave Temple, Thirunanthikarai, Kanyakumari – 629161",
        "Keeriparai Reserve Forest, Keeriparai, Kanyakumari – 629401",
        "Mahatma Gandhi Memorial Rock, Vavathurai, Kanyakumari – 629702",
        "Sunset View Point, Kanyakumari Pier, Kanyakumari – 629702"
    ],
            "karur": [
        "Arulmigu Sadasiva Brahmendral Adhistanam, Nerur, Karur – 639117",
        "Arulmigu Kalyana Pasupatheswarar Temple, Karur – 639001",
        "Arulmigu Mariamman Temple, Karur – 639001",
        "Vennaimalai Murugan Temple, Vennaimalai, Karur – 639206",
        "Ponnaniyar Dam, Pooncholai Village, Kadavoor Hill Region, Karur – 639114",
        "Uthiyur Hills, Uthiyur, Karur – 639206",
        "Uthanda Velayudhasamy Temple, Uthiyur Hills, Karur – 639206",
        "Uchi Pillayar Temple, Uthiyur Hills, Karur – 639206",
        "Konganar Siddhar Samadhi, Uthiyur Hills, Karur – 639206",
        "Government Museum, Karur – 639001",
        "Thirukkampuliyur Amma Park, Thirukkampuliyur, Karur – 639114",
        "Mayanur Kamarajar Lake, Mayanur, Karur – 639113",
        "Arulmigu Kashi Vishwanatha Temple, Nerur, Karur – 639117",
        "Iyermalai Siva Temple, Iyermalai, Karur – 639206",
        "Lalapet Iyyapan Temple, Lalapet, Karur – 639114",
        "Togamalai Murugan Temple, Togamalai, Karur – 639206",
        "Vyakarapuriswarar Temple, Vyakarapuram, Karur – 639206",
        "Abayapradhana Ranganathar Temple, Abayapuri, Karur – 639206",
        "Thanthondrimalai Kalyana Venkataramanaswamy Temple, Thanthondrimalai, Karur – 639206",
        "Pugazhimalai Arupadai Murugan Temple, Pugazhimalai, Karur – 639206",
        "Vangal Pudhu Vangalamman Temple, Vangal, Karur – 639206",
        "Madhukkarai Sellandiyamman Temple, Madhukkarai, Karur – 639206",
        "Manmangalam Puthu Kaliyamman Temple, Manmangalam, Karur – 639206",
        "Kadavur Vasantha Perumal Temple, Kadavur, Karur – 639206",
        "Kulithalai Neelameegha Perumal Temple, Kulithalai, Karur – 639114",
        "Shivayam Siva Temple, Shivayam, Karur – 639206",
        "Lalapet Sri Jaya Anjaneya, Lalapet, Karur – 639114",
        "Rangamalai Malleeshwarar Temple, Rangamalai, Karur – 639206"
    ],
             "krishnagiri": [
        "Shree Parshwa Padmavathi Shaktipeet Tirth Dham, Sadhanpalli, Sundampatti Post, Krishnagiri – 635108",
        "Sri Kattu Veera Anjaneya Temple, Dakshina Tirupathi, Gopasandram-Kamandoodi, Shoolagiri, Krishnagiri – 635117",
        "Arulmigu Maragathamigai Chandra Choodeshwara Temple, Hosur, Krishnagiri – 635109",
        "Krishnagiri Fort, Krishnagiri – 635001",
        "KRP Dam (Krishnagiri Reservoir Project), Krishnagiri – 635001",
        "Rayakottah Fort, Rayakottai, Krishnagiri – 635116",
        "Betrayaswamy Temple, Denkanikottai, Krishnagiri – 635107",
        "Varadaraja Perumal Temple, Shoolagiri, Krishnagiri – 635117",
        "Penneswaraar Temple, Pennagaram, Krishnagiri – 635113",
        "Thally Valley, Thally, Krishnagiri – 635118",
        "Government Museum, Krishnagiri – 635001",
        "Kelevarapalli Reservoir, Hosur, Krishnagiri – 635109",
        "Shoolagiri Hills, Shoolagiri, Krishnagiri – 635117",
        "Melagiri Hills, Denkanikottai, Krishnagiri – 635107",
        "Hogenakkal Falls, near Pennagaram, Krishnagiri – 635113"
    ],
             "madurai": [
        "Meenakshi Amman Temple, Madurai Main, Madurai – 625001",
        "Thirumalai Nayakkar Mahal, Panthadi 1st Street, Madurai – 625001",
        "Gandhi Memorial Museum, Tamukkam, Madurai – 625020",
        "Alagar Kovil, Alagarkoil Road, Madurai – 625301",
        "Vandiyur Mariamman Teppakulam, Vandiyur, Madurai – 625020",
        "Koodal Azhagar Temple, Periyar, Madurai – 625001",
        "St. Mary's Cathedral, East Veli Street, Madurai – 625001",
        "ISKCON Temple, Surveyor Colony, Madurai – 625007",
        "Thiruparankundram Murugan Temple, Thiruparankundram, Madurai – 625005",
        "Samanar Hills, Keelakuyilkudi Village, Madurai – 625019",
        "Pazhamudhir Solai, Azhagar Malai Hills, Madurai – 625301",
        "Goripalayam Dargah, Goripalayam, Madurai – 625002",
        "Kazimar Big Mosque, Kazimar Street, Madurai – 625001",
        "MGR Race Course Stadium, Race Course Road, Madurai – 625002",
        "Rajaji Park, K.K. Nagar, Madurai – 625020"
    ],
              "mayiladuthurai": [
        "Mayuranathaswami Temple, Mayiladuthurai – 609001",
        "Parimala Ranganatha Perumal Temple, Thiruvilandur, Mayiladuthurai – 609001",
        "Vaitheeswaran Koil, Vaitheeswaran Koil, Mayiladuthurai – 609117",
        "Poompuhar Beach, Poompuhar, Mayiladuthurai – 609105",
        "Silappathikara Art Gallery, Poompuhar, Mayiladuthurai – 609105",
        "Danish Fort (Fort Dansborg), Tharangambadi, Mayiladuthurai – 609313",
        "Zion Church, Tharangambadi, Mayiladuthurai – 609313",
        "Thirumanancheri Temple, Thirumanancheri, Mayiladuthurai – 609801",
        "Sattainathar Temple, Sirkazhi, Mayiladuthurai – 609110",
        "Ayyarapper Temple, Thiruvaiyaru, Mayiladuthurai – 613204",
        "Thula Kattam (Cauvery River Bathing Ghat), Mayiladuthurai – 609001",
        "Navagraha Temples Circuit, Various locations, Mayiladuthurai District",
        "Amritaghateswarar-Abirami Temple, Thirukkadaiyur, Mayiladuthurai – 609311",
        "Sri Kamatchi Amman Temple, Mayiladuthurai – 609001",
        "Sri Muthumariamman Temple, Mayiladuthurai – 609001",
        "Mayiladuthurai Boat House, Mayiladuthurai – 609001"
    ],
              "nagapattinam": [
        "Basilica of Our Lady of Good Health, Velankanni, Nagapattinam – 611111",
        "Nagore Dargah Shariff, Nagore, Nagapattinam – 611002",
        "Kayarohanaswami Temple, Nagapattinam – 611001",
        "Soundararaja Perumal Temple, Nagapattinam – 611001",
        "Sikkal Singaravelar Temple, Sikkal, Nagapattinam – 611108",
        "Ettukudi Murugan Temple, Ettukudi, Nagapattinam – 609501",
        "Vaitheeswaran Koil, Vaitheeswaran Koil, Nagapattinam – 609117",
        "Brahmapureeswarar Temple, Thirukkuvalai, Nagapattinam – 610204",
        "Loganatha Perumal Temple, Thirukannangudi, Nagapattinam – 609001",
        "Point Calimere Wildlife and Bird Sanctuary, Kodiakkarai, Nagapattinam – 614807",
        "Nagapattinam Beach, Nagapattinam – 611001",
        "Velankanni Beach, Velankanni, Nagapattinam – 611111",
        "Nagapattinam Lighthouse, Nagapattinam – 611001",
        "Dutch Fort, Tranquebar, Nagapattinam – 609313",
        "Archaeological Museum, Tranquebar, Nagapattinam – 609313",
        "Government Museum, Nagapattinam – 611001",
        "Nellukkadai Mariamman Temple, Nagapattinam – 611001",
        "Vettar Rivermouth View Point, Nagapattinam – 611001",
        "Thirunagai Divya Desam, Nagapattinam – 611001",
        "Koothanur Maha Saraswathi Temple, Koothanur, Nagapattinam – 609801"
    ],
               "namakkal": [
        "Namakkal Anjaneyar Temple, Namakkal – 637001",
        "Namakkal Narasimha Swamy Temple, Namakkal – 637001",
        "Namagiri Amman Temple, Namakkal – 637001",
        "Namakkal Fort, Namakkal – 637001",
        "Kolli Hills, Namakkal District – 637411",
        "Agaya Gangai Waterfalls, Kolli Hills, Namakkal District – 637411",
        "Arapaleeswarar Temple, Kolli Hills, Namakkal District – 637411",
        "Ettukai Amman Temple, Kolli Hills, Namakkal District – 637411",
        "Seeku Parai View Point, Kolli Hills, Namakkal District – 637411",
        "Thathagiri Murugan Temple, Muthugapatti, Namakkal – 637405",
        "Ardhanareeswarar Temple, Tiruchengode, Namakkal District – 637211",
        "Asaladeebesvarar Temple, Mohanur, Namakkal District – 637015",
        "Navaladi Karuppuswami Temple, Mohanur, Namakkal District – 637015",
        "Jedarpalayam Dam, Jedarpalayam, Namakkal District – 637213",
        "Botanical Garden, Kolli Hills, Namakkal District – 637411",
        "Siddhar Caves, Kolli Hills, Namakkal District – 637411",
        "Maasila Falls, Kolli Hills, Namakkal District – 637411",
        "Kalipatti Kandaswamy Temple, Kalipatti, Namakkal District – 637404"
    ],
                "perambalur": [
        "Ranjankudi Fort, Ranjankudi, Perambalur – 621212",
        "Siruvachur Sri Madhurakaliamman Temple, Siruvachur, Perambalur – 621113",
        "Sri Bala Dhandayuthapani Swamy Temple, Chettikulam, Perambalur – 621104",
        "Ekambareswarar Temple, Chettikulam, Perambalur – 621104",
        "National Fossil Wood Park, Sathanur, Perambalur – 621106",
        "Visvakudi Dam, Visvakudi, Perambalur – 621115",
        "Arulmigu Mariamman Temple, Perambalur – 621212",
        "Perambalur Government Museum, Perambalur – 621212",
        "CSI St. Paul's Church, Perambalur – 621212",
        "Puduvettakudi Vinayagar & Mariamman Temple, Puduvettakudi, Perambalur – 621212",
        "Thiru Sitrambalam Temple, Perambalur – 621212",
        "Masjid NH-45 Padalur Jumma Mosque, Padalur, Perambalur – 621109",
        "Rapha AG Church, Perambalur – 621212",
        "Periyar Park, Perambalur – 621212",
        "Karugudi Lake, Karugudi, Perambalur – 621212"
    ],
                 "pudukkottai": [
        "Sittanavasal Cave (Arivar Koil), Sittanavasal Village, Pudukkottai – 622101",
        "Thirumayam Fort, Thirumayam, Pudukkottai – 622507",
        "Avudaiyarkoil (Athmanathaswamy Temple), Avudaiyarkoil, Pudukkottai – 614618",
        "Kudumiyanmalai Temple, Kudumiyanmalai, Pudukkottai – 622104",
        "Brahadambal Temple, Pudukkottai Town, Pudukkottai – 622001",
        "Narthamalai Temples, Narthamalai, Pudukkottai – 622404",
        "Kunnandarkoil Cave Temple, Kunnandarkoil, Pudukkottai – 622002",
        "Periyanayagi Madha Shrine (Avur Church), Avur, Pudukkottai – 622515",
        "Viralimalai Murugan Temple, Viralimalai, Pudukkottai – 621316",
        "Viralimalai Bird Sanctuary, Viralimalai, Pudukkottai – 621316",
        "Government Museum, Pudukkottai Town, Pudukkottai – 622001",
        "Pudukkottai Palace, Pudukkottai Town, Pudukkottai – 622001",
        "Sathyagirisvarar Temple, Thirumayam, Pudukkottai – 622507",
        "Sathyamurthi Perumal Temple, Thirumayam, Pudukkottai – 622507",
        "Chithannavasal Jain Beds, Sittanavasal, Pudukkottai – 622101"
    ],
                 "ramanathapuram": [
        "Arulmigu Ramanathaswamy Temple, Rameswaram, Ramanathapuram – 623526",
        "Dhanushkodi Beach, Dhanushkodi, Ramanathapuram – 623526",
        "Pamban Bridge, Pamban, Ramanathapuram – 623521",
        "Dr. A.P.J. Abdul Kalam Memorial, Pei Karumbu, Rameswaram, Ramanathapuram – 623526",
        "House of Kalam (Dr. A.P.J. Abdul Kalam House), Mosque Street, Rameswaram, Ramanathapuram – 623526",
        "Uthirakosamangai Mangalanathar Temple, Uthirakosamangai, Ramanathapuram – 623533",
        "Adhi Ratneswarar Temple, Thiruvadanai, Ramanathapuram – 623407",
        "Ramanathapuram Palace, Ramanathapuram – 623501",
        "Ariyaman Beach, Sattakkonvalasai, Ramanathapuram – 623531",
        "Villoondi Tirtham, Rameswaram, Ramanathapuram – 623526",
        "Agni Theertham, Rameswaram, Ramanathapuram – 623526",
        "Kurusadai Island, Gulf of Mannar, Ramanathapuram – 623526",
        "Gulf of Mannar Marine National Park, Mandapam, Ramanathapuram – 623518",
        "Chitrangudi Bird Sanctuary, Mudukulathur, Ramanathapuram – 623704",
        "Kanjirankulam Bird Sanctuary, Mudukulathur, Ramanathapuram – 623704",
        "Mangalanathar Temple, Uthirakosamangai, Ramanathapuram – 623533",
        "Thiruppullani Aadhi Jagannatha Perumal Temple, Thiruppullani, Ramanathapuram – 623532",
        "Devipattinam Navabashanam Temple, Devipattinam, Ramanathapuram – 623514",
        "Vivekananda Memorial, Kundhukal, Ramanathapuram – 623526",
        "Palai Genetic Heritage Garden, Achadiparambu, Ramanathapuram – 623501",
        "Periyapattinam Beach, Periyapattinam, Ramanathapuram – 623523",
        "R.S. Madai Sea World Aquarium, Rameswaram, Ramanathapuram – 623526",
        "Thiruvettriyur Baagam Piriyal Temple, Thiruvettriyur, Ramanathapuram – 623520",
        "Irumeni Village (Sweet Water Wells), Irumeni, Ramanathapuram – 623534",
        "Panaikkulam Beach, Panaikkulam, Ramanathapuram – 623531",
        "Puthuvalasai Beach, Puthuvalasai, Ramanathapuram – 623531",
        "Attrangarai Beach, Attrangarai, Ramanathapuram – 623531",
        "Valoor Beach, Valoor, Ramanathapuram – 623531"
    ],
                  "ranipet": [
        "Arulmigu Balamurugan Ratnagiri Tirukkovil, Ratnagiri, Ranipet – 632513",
        "Vallimalai Murugan Hill Temple, Vallimalai, Ranipet – 632510",
        "Arulmigu Lakshmi Narasimha Swamy Temple, Arakkonam, Ranipet – 631001",
        "Delhi Gate, Arcot, Ranipet – 632503",
        "Thirukkadigai Temple, Sholinghur, Ranipet – 631102",
        "Ghatikachala Hill, Sholinghur, Ranipet – 631102",
        "Arulmigu Prasanna Venkatesa Perumal Temple, Kaveripakkam, Ranipet – 632501",
        "Walajapet Kasiviswanathar Temple, Walajapet, Ranipet – 632513",
        "Amirthi Zoological Park, Amirthi, Ranipet – 632501",
        "Green Thunder Water Theme Park, Walajapet, Ranipet – 632513",
        "Palar River, Ranipet – 632001",
        "Arcot Lakshmi Theatre, Arcot, Ranipet – 632503",
        "DR Theatre, Ranipet – 632001",
        "Rajeshwari Theater, Ranipet – 632001"
    ],
                   "salem": [
        "Yercaud Hill Station, Yercaud, Salem – 636601",
        "Mettur Dam, Mettur, Salem – 636401",
        "1008 Lingam Temple, Ariyanoor, Salem – 636308",
        "Kalangi Siddhar Temple, Kanja Malai, Salem – 636305",
        "Kottai Mariamman Temple, Fort, Salem – 636001",
        "Sugavaneswarar Temple, Fort, Salem – 636001",
        "Kottai Perumal Temple (Alagirinathar Temple), Fort, Salem – 636001",
        "Kurumbapatti Zoological Park, Kurumbapatti, Salem – 636008",
        "Mookaneri Lake, Kannankurichi, Salem – 636008",
        "Paravasa Ulagam Water Theme Park, Mallur, Salem – 636203",
        "Sankagiri Fort, Sankagiri, Salem – 637301",
        "Oothumalai Murugan Temple, Oothumalai, Salem – 636007",
        "Kumaragiri Murugan Temple, Udayapatti, Salem – 636140",
        "Poiman Karadu Viewpoint, Panamarathupatti, Salem – 636204",
        "Anna Park, Yercaud, Salem – 636601",
        "Kiliyur Falls, Yercaud, Salem – 636601",
        "Shevaroy Temple, Shevaroy Hills, Yercaud, Salem – 636601",
        "Siddhar Temple, Kanja Malai, Salem – 636305",
        "Kailasanathar Temple, Tharamangalam, Salem – 636502",
        "Attur Fort, Attur, Salem – 636102",
        "Vinayaka Missions 1008 Lingam Temple, Ariyanoor, Salem – 636308",
        "Salem Government Museum, Fort, Salem – 636001",
        "Jamia Masjid, Fort, Salem – 636001",
        "Christ Church, Fort Road, Salem – 636001",
        "Lechler Memorial Church, Fort, Salem – 636001",
        "Kumaragiri Lake, Udayapatti, Salem – 636140",
        "Silk Farm, Yercaud, Salem – 636601",
        "Green Valley Viewpoint, Yercaud, Salem – 636601",
        "Lady's Seat, Yercaud, Salem – 636601",
        "Gent's Seat, Yercaud, Salem – 636601",
        "Pagoda Point, Yercaud, Salem – 636601",
        "Botanical Garden, Yercaud, Salem – 636601",
        "Bear's Cave, Yercaud, Salem – 636601",
        "Deer Park, Yercaud, Salem – 636601",
        "Children's Seat, Yercaud, Salem – 636601",
        "Rose Garden, Yercaud, Salem – 636601",
        "Orchidarium, Yercaud, Salem – 636601",
        "Sri Muth Malai Murugan Temple, Puthiragoundampalayam, Salem – 636005",
        "Thanthondreeswarar Temple, Belur, Salem – 636104",
        "Sowriyur, Salem – 636001",
        "Poolampatty Waterfalls, Poolampatty, Salem – 636113",
        "Anayampatty Swedha Nadhi, Gangavalli, Salem – 636105",
        "Koppu Konda Perumal Malai, Pethanaickenpalayam, Salem – 636109",
        "Atkonteshwarar Temple, Pethanaickenpalayam, Salem – 636109",
        "Salem Ramanujar Manimandapam, Erumapalayam, Salem – 636015",
        "Muttal Falls, Muttal, Salem – 636112"
    ],
                    "sivaganga": [
        "Pillayarpatti Karpaga Vinayagar Temple, Pillayarpatti, Sivaganga – 630108",
        "Vettangudi Bird Sanctuary, Vettangudipatti, Sivaganga – 630211",
        "Aayiram Jannal Veedu (Thousand Pillars House), Karaikudi, Sivaganga – 630001",
        "Kaviarasu Kannadasan Manimandapam, Karaikudi, Sivaganga – 630001",
        "Sivaganga Palace, Sivaganga Town, Sivaganga – 630561",
        "Keezhadi Archaeological Site & Museum, Keezhadi, Sivaganga – 630553",
        "Chettinad Mansions, Kanadukathan, Sivaganga – 630103",
        "Thirumalai Cave Temple, Thirumalai, Sivaganga – 630561",
        "Kundrakudi Murugan Temple, Kundrakudi, Sivaganga – 630106",
        "Kollangudi Kaliamman Temple, Kollangudi, Sivaganga – 630108",
        "Madapuram Kaliamman Temple, Madapuram, Sivaganga – 630561",
        "Thayamangalam Muthumariamman Temple, Thayamangalam, Sivaganga – 630561",
        "Kaleeswarar Temple, Kalayarkoil, Sivaganga – 630551",
        "Sivaganga District Museum, Sivaganga Town, Sivaganga – 630561",
        "Vallal Alagappa Chettiyar Museum, Karaikudi, Sivaganga – 630001",
        "Vintage Car & Bike Museum, Pillayarpatti, Sivaganga – 630108",
        "Panchabhutheswaram Temple, Vedhiyanendal, Sivaganga – 630611",
        "Marudhupandiyar Fort, Siruvayal, Sivaganga – 630561",
        "Sangarappatti Fort, Amaravathi Pudur, Sivaganga – 630561",
        "Velunachiyar Memorial Hall, Sivaganga Town, Sivaganga – 630561",
        "Piranmalai Kodunkundreeswarar Temple, Piranmalai, Sivaganga – 630561",
        "Idaikattur Sacred Heart Church, Idaikattur, Sivaganga – 630561",
        "Syed Ibrahim Shahid Dargah, Ervadi, Sivaganga – 630561",
        "Thirukoshtiyur Sowmya Narayana Perumal Temple, Thirukoshtiyur, Sivaganga – 630561",
        "Pillaiyarpatti Vinayagar Temple, Pillayarpatti, Sivaganga – 630108",
        "Koviloor Temple, Karaikudi, Sivaganga – 630001",
        "Maranadu Karuppanaswamy Temple, Maranadu, Sivaganga – 630561",
        "Manamadurai Sri Veera Azhagar Temple, Manamadurai, Sivaganga – 630606",
        "Ilayangudi Rajendra Chola Eswara Temple, Ilayangudi, Sivaganga – 630702",
        "Nattarasankottai Shri Kannathal Temple, Nattarasankottai, Sivaganga – 630601",
        "Sree Sornamoortheeshwarar Temple, Kandadevi, Sivaganga – 630611",
        "Kollakalaiamman Temple, Kollakalai, Sivaganga – 630561",
        "Kallal Somasundaram Soundara Nayagi Temple, Kallal, Sivaganga – 630305",
        "Sri Malaikoluntheeswarar Temple, Thirumalai, Sivaganga – 630561",
        "Sri Thiruvengadamudaiyan Temple, Ariyakudi, Sivaganga – 630561",
        "Vairava Swamy & Poomalachiyamman Temple, N.Vairavanpatti, Sivaganga – 630561",
        "Pattamangalam Guru Bagavan Temple, Pattamangalam, Sivaganga – 630561",
        "Idaikattur Sacred Heart Shrine, Idaikattur, Sivaganga – 630561",
        "Syed Salaar Sha Shaheed Dargah, Pallichandai, Sivaganga – 630561",
        "Vediyerendal Sri Angala Parameswari Amman Temple, Vediyerendal, Sivaganga – 630561",
        "Sri Aathi Thiruththalinaathar Temple, Tirupattur, Sivaganga – 630561",
        "Manomaya Buddha Temple, Paganeri, Sivaganga – 630561",
        "Manamadurai Clay Itracs, Manamadurai, Sivaganga – 630561",
        "Tirupachi Billhooks, Tiruppachetti, Sivaganga – 630561",
        "Sivaganga Graphite Mines, Sivaganga Town, Sivaganga – 630561",
        "Singampunari Coir Industry, Singampunari, Sivaganga – 630561"
    ],
                    "tenkasi": [
        "Sri Kasi Viswanathar Temple (Ulagamman Temple), Tenkasi – 627811",
        "Courtallam (Kutralam) Waterfalls, Courtallam, Tenkasi – 627802",
        "Thirumalai Kovil (Murugan Temple), Panpoli, Tenkasi – 627852",
        "Sivasailam Temple, Sivasailam, Tenkasi – 627852",
        "Aintharuvi (Five Falls), Courtallam, Tenkasi – 627802",
        "Sankara Narayanasamy Temple, Sankarankovil, Tenkasi – 627756",
        "Thirumalapuram Rock-Cut Cave Temples, Thirumalapuram, Tenkasi – 627859",
        "Ayikudi Balasubramanya Swamy Temple, Ayikudi, Tenkasi – 627853",
        "Thirukutralanathar Temple, Courtallam, Tenkasi – 627802",
        "Mekkarai Amusement Park, Courtallam, Tenkasi – 627802"
    ],
                    "thanjavur": [
        "Brihadeeswarar Temple, South Bank Road, Thanjavur – 613007",
        "Thanjavur Maratha Palace, Thanjavur – 613001",
        "Saraswathi Mahal Library, Thanjavur – 613001",
        "Sivaganga Park, Thanjavur – 613007",
        "Rajaraja Chola Art Gallery, Thanjavur – 613007",
        "Vijayanagar Fort, Thanjavur – 613009",
        "Manora Fort, Manora, Thanjavur – 614101",
        "Alangudi Temple, Alangudi, Thanjavur – 614202",
        "Thanjavur Royal Palace, Thanjavur – 613001",
        "Swamimalai Temple, Swamimalai, Thanjavur – 612302",
        "Shivaganga Park, Thanjavur – 613007"
    ],
                     "nilgiris": [
        "Ooty (Udhagamandalam), Nilgiris – 643001",
        "Botanical Gardens, Ooty, Nilgiris – 643001",
        "Ooty Lake, Ooty, Nilgiris – 643001",
        "Doddabetta Peak, Ooty, Nilgiris – 643001",
        "Rose Garden, Ooty, Nilgiris – 643001",
        "Pykara Lake, Pykara, Nilgiris – 643224",
        "Mudumalai Wildlife Sanctuary, Masinagudi, Nilgiris – 643223",
        "Nilgiri Mountain Railway (Toy Train), Ooty, Nilgiris – 643001",
        "Coonoor, Nilgiris – 643101",
        "Sim's Park, Coonoor, Nilgiris – 643101",
        "Ketti Valley View, Ketti, Nilgiris – 643215",
        "The Tea Factory and Museum, Ooty, Nilgiris – 643001",
        "Avalanche Lake, Ooty, Nilgiris – 643202",
        "The Tribal Research Centre, Ooty, Nilgiris – 643001"
    ],
                      "theni": [
        "Meghamalai, Theni – 625582",
        "Kumbakarai Waterfalls, Kumbakarai, Theni – 625532",
        "Suruli Waterfalls, Suruli, Theni – 625106",
        "Vaigai Dam, Vaigai, Theni – 625562",
        "Sabarimala, Sabarimala, Theni – 689713",
        "Palaruvi Waterfalls, Sholayur, Theni – 625601",
        "Chinna Suruli Waterfalls, Suruli, Theni – 625106",
        "Griffin's Gate, Thekkady, Theni – 685536",
        "Periyar Wildlife Sanctuary, Thekkady, Theni – 685536"
    ],
                       "thiruvallur": [
        "Veeratteswarar Temple, Thiruvallur – 601201",
        "Sri Lakshmi Hayagriva Perumal Temple, Thiruvallur – 601201",
        "Padi Kaaliamman Temple, Padi, Thiruvallur – 600050",
        "Kailasanathar Temple, Kanchipuram Road, Thiruvallur – 601202",
        "Sri Seetha Raman Temple, Thiruvallur – 601201",
        "Aadhi Kesava Perumal Temple, Thiruvallur – 601201",
        "Sri Venugopalaswamy Temple, Thiruvallur – 601201",
        "Bird Sanctuary, Pulicat Lake, Thiruvallur – 601205",
        "Pulicat Lake, Pulicat, Thiruvallur – 601205",
        "Sri Ranganatha Swamy Temple, Thiruvallur – 601201"
    ],
                         "thiruvarur": [
        "Thiruvarur Temple, Thiruvarur – 610001",
        "Vedaranyeswarar Temple, Vedaranyam, Thiruvarur – 614810",
        "Kambu Adhikari Temple, Thiruvarur – 610001",
        "Uppiliappan Temple, Thiruvarur – 610004",
        "Poompuhar Beach, Poompuhar, Thiruvarur – 609107",
        "Azhividhunaathi Temple, Azhividhunaathi, Thiruvarur – 609305",
        "Sri Nithyakalyana Perumal Temple, Thiruvarur – 610001",
        "Brihadeeswarar Temple, Thiruvarur – 610001",
        "Sri Natarajar Temple, Thiruvarur – 610001",
        "Chidambaram Natarajar Temple, Thiruvarur – 610001"
    ],
                         "thoothukudi": [
        "Kattabomman Memorial Fort, Panchalankurichi, Thoothukudi – 628151",
        "Our Lady of Snows Basilica, North Beach Road, Thoothukudi – 628001",
        "Tuticorin Port, Tuticorin – 628001",
        "Sankaranarayanar Temple, Sankarankovil, Thoothukudi – 627756",
        "Panchalankurichi, Thoothukudi – 628151",
        "Sri Vaithiyanatha Swamy Temple, Srivaikundam, Thoothukudi – 628620",
        "Manapad Beach, Manapad, Thoothukudi – 628513",
        "Crocodile Bank, Kanyakumari Road, Thoothukudi – 628002",
        "Thiruchendur Murugan Temple, Thiruchendur, Thoothukudi – 628215",
        "Tiruchendur Beach, Tiruchendur, Thoothukudi – 628215",
        "Adichanallur, Thoothukudi – 628213",
        "Vallanadu Blackbuck Sanctuary, Vallanadu, Thoothukudi – 628211"
    ],
                         "tiruchirapalli": [
        "Sri Ranganathaswamy Temple, Srirangam, Tiruchirapalli – 620006",
        "Rockfort Temple, Rockfort Road, Tiruchirapalli – 620002",
        "Kallanai Dam, Kallanai, Tiruchirapalli – 620105",
        "St. Lourdes Church, Tiruchirapalli – 620001",
        "Jambukeswarar Temple, Thiruvanaikaval, Tiruchirapalli – 620005",
        "Sri Ranganayaki Temple, Srirangam, Tiruchirapalli – 620006",
        "Vayalur Murugan Temple, Vayalur, Tiruchirapalli – 621113",
        "Thiruvanaikaval Temple, Thiruvanaikaval, Tiruchirapalli – 620005",
        "Mukkombu, Upper Anaicut, Tiruchirapalli – 621008",
        "Brahmapureeswarar Temple, Manachanallur, Tiruchirapalli – 621105",
        "Mariamman Temple, Woraiyur, Tiruchirapalli – 620003",
        "Trichy Railway Junction, Tiruchirapalli – 620002",
        "Viralimalai Murugan Temple, Viralimalai, Tiruchirapalli – 621316"
    ],
                          "thirunelveli": [
        "Nellaiappar Temple, Tirunelveli – 627001",
        "Kanthimathi - Nellaiappar Temple, Tirunelveli – 627001",
        "Agasthiyar Falls, Agasthiyar Malai, Tirunelveli – 627852",
        "Kutrallam Waterfalls, Kutrallam, Tirunelveli – 627802",
        "Sri Ramaswamy Temple, Thiruvengadam, Tirunelveli – 627851",
        "Tirunelveli Kinaru, Tirunelveli – 627001",
        "Papanasam, Papanasam, Tirunelveli – 627423",
        "Chenthamaraikulam, Tirunelveli – 627004",
        "Tiruchendur Murugan Temple, Tiruchendur, Thirunelveli – 628215",
        "Vannarpettai, Tirunelveli – 627003",
        "Sri Subramaniya Swamy Temple, Pechiparai, Tirunelveli – 627807"
    ],
                           "thirupathur": [
        "Kundrakudi Murugan Temple, Kundrakudi, Thirupathur – 630206",
        "Jadamalai Temple, Jadamalai, Thirupathur – 630106",
        "Sivaganga, Thirupathur – 630561",
        "Arulmigu Sundara Vinayagar Temple, Thirupathur – 630211",
        "Sundara Vinayagar Temple, Thirupathur – 630211",
        "Kottaiyur, Thirupathur – 630205",
        "Pachaiamman Temple, Thirupathur – 630209"
    ],
                             "thiruppur": [
        "Tiruppur Kumaragurupara Swamy Temple, Tiruppur – 641604",
        "Nilgiri Mountain Railway, Tiruppur – 641666",
        "Uppiliappan Temple, Tiruppur – 641604",
        "Avinashi Temple, Avinashi, Tiruppur – 641654",
        "Ayyappan Temple, Tiruppur – 641601",
        "Kodiveri Dam, Kodiveri, Tiruppur – 641666",
        "Tiruppur Water Tank, Tiruppur – 641602",
        "Kongu Nadu Sivasakthi Temple, Tiruppur – 641603",
        "Sri Veeranarayana Temple, Veerapandi, Tiruppur – 641604"
    ],
                              "thiruvannamalai": [
        "Arunachaleswarar Temple, Arunachala Hill, Thiruvannamalai – 606601",
        "Virupaksha Cave, Arunachala Hill, Thiruvannamalai – 606601",
        "Sri Ramana Maharshi Ashram, Thiruvannamalai – 606603",
        "Ramanashramam, Thiruvannamalai – 606603",
        "Tiruvannamalai Hill, Tiruvannamalai – 606601",
        "Seshadri Swamigal Ashram, Thiruvannamalai – 606601",
        "Agni Theertham, Thiruvannamalai – 606601",
        "Skandashramam, Arunachala Hill, Thiruvannamalai – 606601",
        "Tiruvannamalai Fort, Tiruvannamalai – 606601",
        "Madhava Perumal Temple, Thiruvannamalai – 606601",
        "Pavalakundru, Thiruvannamalai – 606601"
    ],
                               "vellore": [
        "Vellore Fort, Vellore – 632004",
        "Sri Lakshmi Golden Temple, Sripuram, Vellore – 632315",
        "Jalakandeswarar Temple, Vellore Fort, Vellore – 632004",
        "St. John's Church, Vellore – 632004",
        "Vainu Bappu Observatory, Vellore – 632001",
        "Amirthi Zoological Park, Vellore – 632501",
        "Ranganatha Swamy Temple, Vellore – 632003",
        "Sripuram Golden Temple, Sripuram, Vellore – 632315",
        "Balamathi Hill, Vellore – 632008",
        "Baba Institute of Technology, Vellore – 632012"
    ],
                                "villupuram": [
        "Vishnu Kanchi, Villupuram – 605602",
        "Kailasanathar Temple, Villupuram – 605602",
        "Sankaranarayanar Temple, Villupuram – 605602",
        "Thiruvakkarai, Villupuram – 605653",
        "Meenakshi Amman Temple, Villupuram – 605602",
        "Varadaraja Perumal Temple, Villupuram – 605602",
        "Azhagiya Manavalan Perumal Temple, Villupuram – 605602",
        "Siva Temple, Thiruvakkarai, Villupuram – 605653"
    ],
                                 "virudhunagar": [
        "Kottaiyur, Virudhunagar – 626205",
        "Sri Kaliswari Temple, Virudhunagar – 626001",
        "Vallanadu Blackbuck Sanctuary, Vallanadu, Virudhunagar – 626002",
        "Srivilliputhur Andal Temple, Srivilliputhur, Virudhunagar – 626125",
        "Thiruparankundram Murugan Temple, Thiruparankundram, Virudhunagar – 626005",
        "Panchalankurichi, Virudhunagar – 626106",
        "Rajapalayam, Virudhunagar – 626117",
        "Kumaralingam, Virudhunagar – 626128"
    ],
                                 
}

def get_sites_by_place(place_name: str):
    return popular_site.get(place_name.lower(), [])

def find_site_and_pincode(site_query):
    site_query = site_query.lower()
    for district, places in popular_site.items():
        for full_entry in places:
            if site_query in full_entry.lower():
                # Extract pincode
                import re
                match = re.search(r"\b\d{6}\b", full_entry)
                pincode = match.group() if match else None
                return {
                    "full_address": full_entry,
                    "district": district,
                    "pincode": pincode
                }
    return None
